use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use crate::error::Result;
use crate::paths::AppPaths;

pub fn install(paths: &AppPaths) -> Result<Vec<PathBuf>> {
    let shell_dir = paths.shell_dir();
    let zsh_dir = shell_dir.join("zsh");
    fs::create_dir_all(&zsh_dir)?;
    fs::set_permissions(&shell_dir, fs::Permissions::from_mode(0o700))?;
    fs::set_permissions(&zsh_dir, fs::Permissions::from_mode(0o700))?;

    let shortcut_dir = paths.shortcut_bin_dir();
    let launcher = launcher_script(&zsh_dir, &shell_dir.join("bashrc"));
    let bashrc = managed_rc("${WIPSAW_USER_BASHRC:-$HOME/.bashrc}", &shortcut_dir);
    let zshrc = format!(
        "{}export ZDOTDIR={}\n",
        managed_rc("${WIPSAW_USER_ZDOTDIR:-$HOME}/.zshrc", &shortcut_dir),
        shell_quote(&zsh_dir)
    );
    let zprofile = source_zsh_file(".zprofile", &zsh_dir);
    let zshenv = source_zsh_file(".zshenv", &zsh_dir);
    let zlogin = source_zsh_file(".zlogin", &zsh_dir);
    let zlogout = source_zsh_file(".zlogout", &zsh_dir);

    let definitions = [
        (paths.shell_launcher_path(), launcher, 0o755),
        (shell_dir.join("bashrc"), bashrc, 0o600),
        (zsh_dir.join(".zshrc"), zshrc, 0o600),
        (zsh_dir.join(".zprofile"), zprofile, 0o600),
        (zsh_dir.join(".zshenv"), zshenv, 0o600),
        (zsh_dir.join(".zlogin"), zlogin, 0o600),
        (zsh_dir.join(".zlogout"), zlogout, 0o600),
    ];
    let mut installed = Vec::with_capacity(definitions.len());
    for (path, contents, mode) in definitions {
        write_generated_file(&path, &contents, mode)?;
        installed.push(path);
    }
    Ok(installed)
}

fn launcher_script(zsh_dir: &Path, bashrc: &Path) -> String {
    format!(
        "#!/bin/sh\n\
         wipsaw_shell=${{WIPSAW_SHELL:-${{SHELL:-/bin/sh}}}}\n\
         case \"${{wipsaw_shell##*/}}\" in\n\
         \x20 zsh)\n\
         \x20   export WIPSAW_USER_ZDOTDIR=${{ZDOTDIR:-${{HOME}}}}\n\
         \x20   export ZDOTDIR={}\n\
         \x20   exec \"$wipsaw_shell\" -l\n\
         \x20   ;;\n\
         \x20 bash)\n\
         \x20   export WIPSAW_USER_BASHRC=${{WIPSAW_USER_BASHRC:-${{HOME}}/.bashrc}}\n\
         \x20   exec \"$wipsaw_shell\" --noprofile --rcfile {} -i\n\
         \x20   ;;\n\
         \x20 *) exec \"$wipsaw_shell\" -l ;;\n\
         esac\n",
        shell_quote(zsh_dir),
        shell_quote(bashrc),
    )
}

fn managed_rc(user_rc: &str, shortcut_dir: &Path) -> String {
    let codex = shell_quote(&shortcut_dir.join("codex"));
    let manager = shell_quote(&shortcut_dir.join("manager"));
    let lumberg = shell_quote(&shortcut_dir.join("lumberg"));
    let lumbergh = shell_quote(&shortcut_dir.join("lumbergh"));
    format!(
        "# Generated by Wipsaw. The user's rc is sourced before managed overrides.\n\
         if [ -r \"{user_rc}\" ]; then . \"{user_rc}\"; fi\n\
         codex() {{ {codex} \"$@\"; }}\n\
         manager() {{ {manager} \"$@\"; }}\n\
         lumberg() {{ {lumberg} \"$@\"; }}\n\
         lumbergh() {{ {lumbergh} \"$@\"; }}\n"
    )
}

fn source_zsh_file(name: &str, generated_zsh_dir: &Path) -> String {
    format!(
        "# Generated by Wipsaw.\n\
         if [ -r \"${{WIPSAW_USER_ZDOTDIR:-$HOME}}/{name}\" ]; then\n\
         \x20 . \"${{WIPSAW_USER_ZDOTDIR:-$HOME}}/{name}\"\n\
         fi\n\
         export ZDOTDIR={}\n",
        shell_quote(generated_zsh_dir),
    )
}

fn write_generated_file(path: &Path, contents: &str, mode: u32) -> Result<()> {
    let needs_write = fs::read_to_string(path)
        .map(|existing| existing != contents)
        .unwrap_or(true);
    if needs_write {
        fs::write(path, contents)?;
    }
    fs::set_permissions(path, fs::Permissions::from_mode(mode))?;
    Ok(())
}

fn shell_quote(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "'\"'\"'"))
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::install;
    use crate::paths::AppPaths;

    #[test]
    fn generated_rc_sources_user_config_before_overrides() {
        let root = tempdir().unwrap();
        let paths = AppPaths::for_test(root.path());
        paths.ensure().unwrap();
        install(&paths).unwrap();

        let zshrc = fs::read_to_string(paths.shell_dir().join("zsh/.zshrc")).unwrap();
        let source_index = zshrc.find("WIPSAW_USER_ZDOTDIR").unwrap();
        let override_index = zshrc.find("codex() ").unwrap();
        assert!(source_index < override_index);
        assert!(zshrc.contains("shortcuts/bin/codex"));
        assert!(paths.shell_launcher_path().is_file());
    }
}
