use std::env;
use std::ffi::{OsStr, OsString};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use serde::Serialize;

use crate::error::{Result, WipsawError};
use crate::paths::AppPaths;

const TMUX_CONFIG: &str = r#"# Generated by Wipsaw. User tmux configuration is intentionally not loaded.
set-option -g prefix C-b
set-option -g base-index 0
set-option -g renumber-windows on
set-option -g allow-rename off
set-option -g automatic-rename off
set-option -g status on
set-option -g status-position bottom
set-option -g status-interval 2
set-option -g status-style 'bg=#111827,fg=#cbd5e1'
set-option -g status-left-length 24
set-option -g status-left '#[bold,fg=#5eead4] WIPSAW #[default] '
set-option -g status-right '#[fg=#64748b]#{host_short} #[fg=#94a3b8]%H:%M '
set-option -g window-status-format '#[fg=#94a3b8] #I:#W '
set-option -g window-status-current-format '#[bold,bg=#1f2937,fg=#5eead4] #I:#W '
set-option -g pane-border-style 'fg=#334155'
set-option -g pane-active-border-style 'fg=#5eead4'
set-option -g message-style 'bg=#1f2937,fg=#e2e8f0'
set-option -g mode-style 'bg=#0f766e,fg=#f8fafc'
bind-key w if-shell -F '#{@wipsaw_navigator_open}' 'set-option -u @wipsaw_navigator_open; display-popup -C' 'set-option @wipsaw_navigator_open 1; run-shell -C "display-popup -E -w 92% -h 88% -e WIPSAW_PARENT_SESSION=#{session_name} -e WIPSAW_PARENT_WINDOW=#{window_id} wipsaw"'
bind-key c if-shell -F '#{@wipsaw_navigator_open}' 'set-option -u @wipsaw_navigator_open; display-popup -C' 'set-option @wipsaw_navigator_open 1; run-shell -C "display-popup -E -w 92% -h 88% -e WIPSAW_PARENT_SESSION=#{session_name} -e WIPSAW_PARENT_WINDOW=#{window_id} -e WIPSAW_TUI_START=new-tab wipsaw"'
bind-key , if-shell -F '#{@wipsaw_navigator_open}' 'set-option -u @wipsaw_navigator_open; display-popup -C' 'set-option @wipsaw_navigator_open 1; run-shell -C "display-popup -E -w 92% -h 88% -e WIPSAW_PARENT_SESSION=#{session_name} -e WIPSAW_PARENT_WINDOW=#{window_id} -e WIPSAW_TUI_START=rename-tab wipsaw"'
bind-key m run-shell 'manager'
"#;

#[derive(Debug, Clone)]
pub struct TmuxBackend {
    binary: PathBuf,
    socket_name: String,
    config_path: PathBuf,
    path_env: OsString,
    shell_launcher: PathBuf,
}

#[derive(Debug, Clone, Serialize)]
pub struct TmuxWindow {
    pub id: String,
    pub index: i64,
    pub name: String,
    pub active: bool,
    pub cwd: PathBuf,
}

#[derive(Debug, Clone, Serialize)]
pub struct TmuxPaneContext {
    pub session: String,
    pub window_id: String,
    pub window_name: String,
    pub pane_id: String,
}

pub struct CodexTabLaunch<'a> {
    pub session: &'a str,
    pub window_id: &'a str,
    pub cwd: &'a Path,
    pub codex_home: &'a Path,
    pub codex_binary: &'a Path,
    pub managed_thread_id: &'a str,
    pub native_thread_id: &'a str,
    pub return_shell: &'a Path,
}

impl TmuxBackend {
    pub fn from_env(paths: &AppPaths) -> Self {
        let binary = env::var_os("WIPSAW_TMUX_BIN")
            .map(PathBuf::from)
            .or_else(|| {
                paths
                    .bundled_tmux_path()
                    .is_file()
                    .then(|| paths.bundled_tmux_path())
            })
            .unwrap_or_else(|| PathBuf::from("tmux"));
        let socket_name = env::var("WIPSAW_TMUX_SOCKET")
            .ok()
            .filter(|value| !value.trim().is_empty())
            .unwrap_or_else(|| "wipsaw".to_string());
        Self {
            binary,
            socket_name,
            config_path: paths.tmux_config_path(),
            path_env: augmented_path(&paths.shortcut_bin_dir()),
            shell_launcher: paths.shell_launcher_path(),
        }
    }

    pub fn write_config(&self) -> Result<()> {
        let needs_write = fs::read_to_string(&self.config_path)
            .map(|existing| existing != TMUX_CONFIG)
            .unwrap_or(true);
        if needs_write {
            fs::write(&self.config_path, TMUX_CONFIG)?;
        }
        Ok(())
    }

    pub fn reload_config(&self) -> Result<()> {
        let config = self.config_path.as_os_str().to_owned();
        let args = self.base_args(vec![OsString::from("source-file"), config]);
        self.run(&args).map(|_| ())
    }

    pub fn binary(&self) -> &Path {
        &self.binary
    }

    pub fn socket_name(&self) -> &str {
        &self.socket_name
    }

    pub fn version(&self) -> Result<String> {
        let output = Command::new(&self.binary)
            .arg("-V")
            .env("PATH", &self.path_env)
            .output()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        successful_output(&self.binary, &[OsString::from("-V")], output)
    }

    pub fn session_exists(&self, session: &str) -> Result<bool> {
        let args = self.base_args(["has-session", "-t", session]);
        let output = Command::new(&self.binary)
            .args(&args)
            .env("PATH", &self.path_env)
            .output()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        Ok(output.status.success())
    }

    pub fn create_workspace(&self, session: &str, cwd: &Path) -> Result<TmuxWindow> {
        self.write_config()?;
        let args = self.base_args(vec![
            OsString::from("new-session"),
            OsString::from("-d"),
            OsString::from("-P"),
            OsString::from("-F"),
            OsString::from("#{window_id}\x1f#{window_index}\x1f#{window_name}\x1f#{window_active}\x1f#{pane_current_path}"),
            OsString::from("-s"),
            OsString::from(session),
            OsString::from("-n"),
            OsString::from("manager"),
            OsString::from("-c"),
            path_arg(cwd),
            OsString::from("-e"),
            OsString::from("WIPSAW_MANAGED=1"),
            OsString::from("-e"),
            OsString::from(format!("WIPSAW_TMUX_SOCKET={}", self.socket_name)),
            OsString::from("-e"),
            environment_assignment("PATH", &self.path_env),
            OsString::from(shell_quote(self.shell_launcher.as_os_str())),
        ]);
        let output = self.run(&args)?;
        let window = parse_window(output.trim())?;
        self.set_environment(session, "WIPSAW_MANAGED", "1")?;
        self.set_environment(session, "WIPSAW_TMUX_SOCKET", &self.socket_name)?;
        self.set_environment(session, "PATH", &self.path_env.to_string_lossy())?;
        Ok(window)
    }

    pub fn kill_workspace(&self, session: &str) -> Result<()> {
        let args = self.base_args(["kill-session", "-t", session]);
        self.run(&args).map(|_| ())
    }

    pub fn create_tab(&self, session: &str, name: &str, cwd: &Path) -> Result<TmuxWindow> {
        let args = self.base_args(vec![
            OsString::from("new-window"),
            OsString::from("-d"),
            OsString::from("-P"),
            OsString::from("-F"),
            OsString::from("#{window_id}\x1f#{window_index}\x1f#{window_name}\x1f#{window_active}\x1f#{pane_current_path}"),
            OsString::from("-t"),
            OsString::from(session),
            OsString::from("-n"),
            OsString::from(name),
            OsString::from("-c"),
            path_arg(cwd),
            OsString::from(shell_quote(self.shell_launcher.as_os_str())),
        ]);
        parse_window(self.run(&args)?.trim())
    }

    pub fn kill_tab(&self, session: &str, window_id: &str) -> Result<()> {
        let target = format!("{session}:{window_id}");
        let args = self.base_args(["kill-window", "-t", target.as_str()]);
        self.run(&args).map(|_| ())
    }

    pub fn rename_tab(&self, session: &str, window_id: &str, name: &str) -> Result<()> {
        let target = format!("{session}:{window_id}");
        let args = self.base_args(["rename-window", "-t", target.as_str(), name]);
        self.run(&args).map(|_| ())
    }

    pub fn select_tab(&self, session: &str, window_id: &str) -> Result<()> {
        let target = format!("{session}:{window_id}");
        let args = self.base_args(["select-window", "-t", target.as_str()]);
        self.run(&args).map(|_| ())
    }

    pub fn switch_client(&self, session: &str) -> Result<()> {
        let args = self.base_args(["switch-client", "-t", session]);
        self.run(&args).map(|_| ())
    }

    pub fn clear_navigator_guard(&self, session: &str) -> Result<()> {
        let args = self.base_args([
            "set-option",
            "-q",
            "-u",
            "-t",
            session,
            "@wipsaw_navigator_open",
        ]);
        self.run(&args).map(|_| ())
    }

    pub fn window_command(&self, session: &str, window_id: &str) -> Result<String> {
        let target = format!("{session}:{window_id}");
        let args = self.base_args([
            "display-message",
            "-p",
            "-t",
            target.as_str(),
            "#{pane_current_command}",
        ]);
        self.run(&args)
    }

    pub fn current_context(&self) -> Result<TmuxPaneContext> {
        let pane_id = env::var("TMUX_PANE")
            .ok()
            .filter(|value| !value.trim().is_empty())
            .ok_or_else(|| WipsawError::InvalidInput {
                field: "terminal context",
                message: "this shortcut must run inside a Wipsaw tmux tab".to_string(),
            })?;
        let args = self.base_args([
            "display-message",
            "-p",
            "-t",
            pane_id.as_str(),
            "-F",
            "#{session_name}\x1f#{window_id}\x1f#{window_name}\x1f#{pane_id}",
        ]);
        let output = self.run(&args)?;
        let fields = tmux_fields(output.trim());
        if fields.len() != 4 {
            return Err(WipsawError::MalformedTmuxOutput(output));
        }
        Ok(TmuxPaneContext {
            session: fields[0].to_string(),
            window_id: fields[1].to_string(),
            window_name: fields[2].to_string(),
            pane_id: fields[3].to_string(),
        })
    }

    pub fn launch_codex_in_tab(&self, launch: CodexTabLaunch<'_>) -> Result<()> {
        let target = format!("{}:{}", launch.session, launch.window_id);
        let command = codex_launch_command(
            launch.cwd,
            launch.codex_home,
            launch.codex_binary,
            launch.managed_thread_id,
            launch.native_thread_id,
            &self.shell_launcher,
        );
        let args = self.base_args(vec![
            OsString::from("respawn-pane"),
            OsString::from("-k"),
            OsString::from("-t"),
            OsString::from(target),
            OsString::from(command),
        ]);
        self.run(&args).map(|_| ())
    }

    pub fn list_windows(&self, session: &str) -> Result<Vec<TmuxWindow>> {
        let args = self.base_args([
            "list-windows",
            "-t",
            session,
            "-F",
            "#{window_id}\x1f#{window_index}\x1f#{window_name}\x1f#{window_active}\x1f#{pane_current_path}",
        ]);
        self.run(&args)?
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(parse_window)
            .collect()
    }

    pub fn attach(&self, session: &str) -> Result<()> {
        let args = self.base_args(["attach-session", "-t", session]);
        let status = Command::new(&self.binary)
            .args(&args)
            .env("PATH", &self.path_env)
            .env_remove("TMUX")
            .env_remove("TMUX_PANE")
            .status()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        if status.success() {
            Ok(())
        } else {
            Err(WipsawError::CommandFailed {
                program: self.binary.display().to_string(),
                args: args_text(&args),
                code: status.code(),
                stderr: "tmux attach failed".to_string(),
            })
        }
    }

    fn set_environment(&self, session: &str, name: &str, value: &str) -> Result<()> {
        let args = self.base_args(["set-environment", "-t", session, name, value]);
        self.run(&args).map(|_| ())
    }

    fn base_args<I, S>(&self, args: I) -> Vec<OsString>
    where
        I: IntoIterator<Item = S>,
        S: Into<OsString>,
    {
        let mut result = vec![
            OsString::from("-L"),
            OsString::from(&self.socket_name),
            OsString::from("-f"),
            self.config_path.as_os_str().to_owned(),
        ];
        result.extend(args.into_iter().map(Into::into));
        result
    }

    fn run(&self, args: &[OsString]) -> Result<String> {
        let output = Command::new(&self.binary)
            .args(args)
            .env("PATH", &self.path_env)
            .output()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        successful_output(&self.binary, args, output)
    }
}

fn augmented_path(shortcut_bin_dir: &Path) -> OsString {
    let existing = env::var_os("PATH").unwrap_or_default();
    let entries =
        std::iter::once(shortcut_bin_dir.to_path_buf()).chain(env::split_paths(&existing));
    env::join_paths(entries).unwrap_or(existing)
}

fn environment_assignment(name: &str, value: &OsStr) -> OsString {
    let mut assignment = OsString::from(name);
    assignment.push("=");
    assignment.push(value);
    assignment
}

fn successful_output(program: &Path, args: &[OsString], output: Output) -> Result<String> {
    if output.status.success() {
        return Ok(String::from_utf8_lossy(&output.stdout).trim().to_string());
    }
    Err(WipsawError::CommandFailed {
        program: program.display().to_string(),
        args: args_text(args),
        code: output.status.code(),
        stderr: String::from_utf8_lossy(&output.stderr).trim().to_string(),
    })
}

fn args_text(args: &[OsString]) -> String {
    args.iter()
        .map(|arg| arg.to_string_lossy())
        .collect::<Vec<_>>()
        .join(" ")
}

fn path_arg(path: &Path) -> OsString {
    path.as_os_str().to_owned()
}

fn codex_launch_command(
    cwd: &Path,
    codex_home: &Path,
    codex_binary: &Path,
    managed_thread_id: &str,
    native_thread_id: &str,
    return_command: &Path,
) -> String {
    format!(
        "cd {} && env CODEX_HOME={} WIPSAW_THREAD_ID={} WIPSAW_NATIVE_THREAD_ID={} {} resume {}; exec {}",
        shell_quote(cwd.as_os_str()),
        shell_quote(codex_home.as_os_str()),
        shell_quote(OsStr::new(managed_thread_id)),
        shell_quote(OsStr::new(native_thread_id)),
        shell_quote(codex_binary.as_os_str()),
        shell_quote(OsStr::new(native_thread_id)),
        shell_quote(return_command.as_os_str()),
    )
}

fn shell_quote(value: &OsStr) -> String {
    format!("'{}'", value.to_string_lossy().replace('\'', "'\"'\"'"))
}

fn parse_window(line: &str) -> Result<TmuxWindow> {
    // tmux renders non-printing format separators as octal escapes when it
    // serializes formatted output (US, 0x1f, becomes the four bytes `\\037`).
    // Keep accepting the raw separator as well for compatibility with tmux
    // versions or control-mode transports that preserve it.
    let fields = tmux_fields(line);
    if fields.len() != 5 {
        return Err(WipsawError::MalformedTmuxOutput(line.to_string()));
    }
    Ok(TmuxWindow {
        id: fields[0].to_string(),
        index: fields[1]
            .parse()
            .map_err(|_| WipsawError::MalformedTmuxOutput(line.to_string()))?,
        name: fields[2].to_string(),
        active: fields[3] == "1",
        cwd: PathBuf::from(fields[4]),
    })
}

fn tmux_fields(line: &str) -> Vec<&str> {
    if line.contains("\\037") {
        line.split("\\037").collect::<Vec<_>>()
    } else {
        line.split('\x1f').collect::<Vec<_>>()
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{TMUX_CONFIG, codex_launch_command, parse_window};

    #[test]
    fn popup_bindings_expand_the_parent_context_before_launch() {
        assert!(TMUX_CONFIG.contains(
            "run-shell -C \"display-popup -E -w 92% -h 88% -e WIPSAW_PARENT_SESSION=#{session_name}"
        ));
        assert!(TMUX_CONFIG.contains("-e WIPSAW_PARENT_WINDOW=#{window_id}"));
    }

    #[test]
    fn window_format_is_parsed() {
        let window = parse_window("@3\x1f2\x1fapi\x1f1\x1f/tmp/project").unwrap();
        assert_eq!(window.id, "@3");
        assert_eq!(window.index, 2);
        assert_eq!(window.name, "api");
        assert!(window.active);
    }

    #[test]
    fn tmux_octal_escaped_separator_is_parsed() {
        let window = parse_window("@3\\0372\\037api\\0371\\037/tmp/project").unwrap();
        assert_eq!(window.id, "@3");
        assert_eq!(window.index, 2);
        assert_eq!(window.cwd.to_string_lossy(), "/tmp/project");
    }

    #[test]
    fn codex_launch_is_shell_quoted_and_returns_to_the_shell() {
        let command = codex_launch_command(
            Path::new("/tmp/Jordan's project"),
            Path::new("/tmp/codex home"),
            Path::new("/opt/Codex CLI/codex"),
            "thread_managed",
            "native-123",
            Path::new("/bin/zsh"),
        );
        assert!(command.contains("cd '/tmp/Jordan'\"'\"'s project'"));
        assert!(command.contains("CODEX_HOME='/tmp/codex home'"));
        assert!(command.contains("'/opt/Codex CLI/codex' resume 'native-123'"));
        assert!(command.ends_with("exec '/bin/zsh'"));
    }
}
