use std::env;
use std::ffi::{OsStr, OsString};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use serde::Serialize;

use crate::error::{Result, WipsawError};
use crate::paths::AppPaths;

const TMUX_CONFIG: &str = r#"# Generated by Wipsaw. User tmux configuration is intentionally not loaded.
set-option -g prefix C-b
set-option -g base-index 0
set-option -g renumber-windows on
set-option -g allow-rename off
set-option -g automatic-rename off
set-option -g status on
set-option -g status-position bottom
set-option -g status-interval 2
set-option -g status-style 'bg=#111827,fg=#cbd5e1'
set-option -g status-left-length 24
set-option -g status-left '#[bold,fg=#5eead4] WIPSAW #[default] '
set-option -g status-right '#[fg=#64748b]#{host_short} #[fg=#94a3b8]%H:%M '
set-option -g window-status-format '#[fg=#94a3b8] #I:#W '
set-option -g window-status-current-format '#[bold,bg=#1f2937,fg=#5eead4] #I:#W '
set-option -g pane-border-style 'fg=#334155'
set-option -g pane-active-border-style 'fg=#5eead4'
set-option -g message-style 'bg=#1f2937,fg=#e2e8f0'
set-option -g mode-style 'bg=#0f766e,fg=#f8fafc'
"#;

#[derive(Debug, Clone)]
pub struct TmuxBackend {
    binary: PathBuf,
    socket_name: String,
    config_path: PathBuf,
}

#[derive(Debug, Clone, Serialize)]
pub struct TmuxWindow {
    pub id: String,
    pub index: i64,
    pub name: String,
    pub active: bool,
    pub cwd: PathBuf,
}

pub struct CodexTabLaunch<'a> {
    pub session: &'a str,
    pub window_id: &'a str,
    pub cwd: &'a Path,
    pub codex_home: &'a Path,
    pub codex_binary: &'a Path,
    pub managed_thread_id: &'a str,
    pub native_thread_id: &'a str,
    pub return_shell: &'a Path,
}

impl TmuxBackend {
    pub fn from_env(paths: &AppPaths) -> Self {
        let binary = env::var_os("WIPSAW_TMUX_BIN")
            .map(PathBuf::from)
            .or_else(|| {
                paths
                    .bundled_tmux_path()
                    .is_file()
                    .then(|| paths.bundled_tmux_path())
            })
            .unwrap_or_else(|| PathBuf::from("tmux"));
        let socket_name = env::var("WIPSAW_TMUX_SOCKET")
            .ok()
            .filter(|value| !value.trim().is_empty())
            .unwrap_or_else(|| "wipsaw".to_string());
        Self {
            binary,
            socket_name,
            config_path: paths.tmux_config_path(),
        }
    }

    pub fn write_config(&self) -> Result<()> {
        let needs_write = fs::read_to_string(&self.config_path)
            .map(|existing| existing != TMUX_CONFIG)
            .unwrap_or(true);
        if needs_write {
            fs::write(&self.config_path, TMUX_CONFIG)?;
        }
        Ok(())
    }

    pub fn binary(&self) -> &Path {
        &self.binary
    }

    pub fn socket_name(&self) -> &str {
        &self.socket_name
    }

    pub fn version(&self) -> Result<String> {
        let output = Command::new(&self.binary)
            .arg("-V")
            .output()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        successful_output(&self.binary, &[OsString::from("-V")], output)
    }

    pub fn session_exists(&self, session: &str) -> Result<bool> {
        let args = self.base_args(["has-session", "-t", session]);
        let output = Command::new(&self.binary)
            .args(&args)
            .output()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        Ok(output.status.success())
    }

    pub fn create_workspace(&self, session: &str, cwd: &Path) -> Result<TmuxWindow> {
        self.write_config()?;
        let args = self.base_args(vec![
            OsString::from("new-session"),
            OsString::from("-d"),
            OsString::from("-P"),
            OsString::from("-F"),
            OsString::from("#{window_id}\x1f#{window_index}\x1f#{window_name}\x1f#{window_active}\x1f#{pane_current_path}"),
            OsString::from("-s"),
            OsString::from(session),
            OsString::from("-n"),
            OsString::from("manager"),
            OsString::from("-c"),
            path_arg(cwd),
        ]);
        let output = self.run(&args)?;
        let window = parse_window(output.trim())?;
        self.set_environment(session, "WIPSAW_MANAGED", "1")?;
        Ok(window)
    }

    pub fn kill_workspace(&self, session: &str) -> Result<()> {
        let args = self.base_args(["kill-session", "-t", session]);
        self.run(&args).map(|_| ())
    }

    pub fn create_tab(&self, session: &str, name: &str, cwd: &Path) -> Result<TmuxWindow> {
        let args = self.base_args(vec![
            OsString::from("new-window"),
            OsString::from("-d"),
            OsString::from("-P"),
            OsString::from("-F"),
            OsString::from("#{window_id}\x1f#{window_index}\x1f#{window_name}\x1f#{window_active}\x1f#{pane_current_path}"),
            OsString::from("-t"),
            OsString::from(session),
            OsString::from("-n"),
            OsString::from(name),
            OsString::from("-c"),
            path_arg(cwd),
        ]);
        parse_window(self.run(&args)?.trim())
    }

    pub fn kill_tab(&self, session: &str, window_id: &str) -> Result<()> {
        let target = format!("{session}:{window_id}");
        let args = self.base_args(["kill-window", "-t", target.as_str()]);
        self.run(&args).map(|_| ())
    }

    pub fn rename_tab(&self, session: &str, window_id: &str, name: &str) -> Result<()> {
        let target = format!("{session}:{window_id}");
        let args = self.base_args(["rename-window", "-t", target.as_str(), name]);
        self.run(&args).map(|_| ())
    }

    pub fn launch_codex_in_tab(&self, launch: CodexTabLaunch<'_>) -> Result<()> {
        let target = format!("{}:{}", launch.session, launch.window_id);
        let command = codex_launch_command(
            launch.cwd,
            launch.codex_home,
            launch.codex_binary,
            launch.managed_thread_id,
            launch.native_thread_id,
            launch.return_shell,
        );
        let args = self.base_args(vec![
            OsString::from("respawn-pane"),
            OsString::from("-k"),
            OsString::from("-t"),
            OsString::from(target),
            OsString::from(command),
        ]);
        self.run(&args).map(|_| ())
    }

    pub fn list_windows(&self, session: &str) -> Result<Vec<TmuxWindow>> {
        let args = self.base_args([
            "list-windows",
            "-t",
            session,
            "-F",
            "#{window_id}\x1f#{window_index}\x1f#{window_name}\x1f#{window_active}\x1f#{pane_current_path}",
        ]);
        self.run(&args)?
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(parse_window)
            .collect()
    }

    pub fn attach(&self, session: &str) -> Result<()> {
        let args = self.base_args(["attach-session", "-t", session]);
        let status = Command::new(&self.binary)
            .args(&args)
            .status()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        if status.success() {
            Ok(())
        } else {
            Err(WipsawError::CommandFailed {
                program: self.binary.display().to_string(),
                args: args_text(&args),
                code: status.code(),
                stderr: "tmux attach failed".to_string(),
            })
        }
    }

    fn set_environment(&self, session: &str, name: &str, value: &str) -> Result<()> {
        let args = self.base_args(["set-environment", "-t", session, name, value]);
        self.run(&args).map(|_| ())
    }

    fn base_args<I, S>(&self, args: I) -> Vec<OsString>
    where
        I: IntoIterator<Item = S>,
        S: Into<OsString>,
    {
        let mut result = vec![
            OsString::from("-L"),
            OsString::from(&self.socket_name),
            OsString::from("-f"),
            self.config_path.as_os_str().to_owned(),
        ];
        result.extend(args.into_iter().map(Into::into));
        result
    }

    fn run(&self, args: &[OsString]) -> Result<String> {
        let output = Command::new(&self.binary)
            .args(args)
            .output()
            .map_err(|error| WipsawError::ExecutableUnavailable {
                program: self.binary.display().to_string(),
                detail: error.to_string(),
            })?;
        successful_output(&self.binary, args, output)
    }
}

fn successful_output(program: &Path, args: &[OsString], output: Output) -> Result<String> {
    if output.status.success() {
        return Ok(String::from_utf8_lossy(&output.stdout).trim().to_string());
    }
    Err(WipsawError::CommandFailed {
        program: program.display().to_string(),
        args: args_text(args),
        code: output.status.code(),
        stderr: String::from_utf8_lossy(&output.stderr).trim().to_string(),
    })
}

fn args_text(args: &[OsString]) -> String {
    args.iter()
        .map(|arg| arg.to_string_lossy())
        .collect::<Vec<_>>()
        .join(" ")
}

fn path_arg(path: &Path) -> OsString {
    path.as_os_str().to_owned()
}

fn codex_launch_command(
    cwd: &Path,
    codex_home: &Path,
    codex_binary: &Path,
    managed_thread_id: &str,
    native_thread_id: &str,
    return_shell: &Path,
) -> String {
    format!(
        "cd {} && env CODEX_HOME={} WIPSAW_THREAD_ID={} WIPSAW_NATIVE_THREAD_ID={} {} resume {}; exec {} -l",
        shell_quote(cwd.as_os_str()),
        shell_quote(codex_home.as_os_str()),
        shell_quote(OsStr::new(managed_thread_id)),
        shell_quote(OsStr::new(native_thread_id)),
        shell_quote(codex_binary.as_os_str()),
        shell_quote(OsStr::new(native_thread_id)),
        shell_quote(return_shell.as_os_str()),
    )
}

fn shell_quote(value: &OsStr) -> String {
    format!("'{}'", value.to_string_lossy().replace('\'', "'\"'\"'"))
}

fn parse_window(line: &str) -> Result<TmuxWindow> {
    // tmux renders non-printing format separators as octal escapes when it
    // serializes formatted output (US, 0x1f, becomes the four bytes `\\037`).
    // Keep accepting the raw separator as well for compatibility with tmux
    // versions or control-mode transports that preserve it.
    let fields = if line.contains("\\037") {
        line.split("\\037").collect::<Vec<_>>()
    } else {
        line.split('\x1f').collect::<Vec<_>>()
    };
    if fields.len() != 5 {
        return Err(WipsawError::MalformedTmuxOutput(line.to_string()));
    }
    Ok(TmuxWindow {
        id: fields[0].to_string(),
        index: fields[1]
            .parse()
            .map_err(|_| WipsawError::MalformedTmuxOutput(line.to_string()))?,
        name: fields[2].to_string(),
        active: fields[3] == "1",
        cwd: PathBuf::from(fields[4]),
    })
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{codex_launch_command, parse_window};

    #[test]
    fn window_format_is_parsed() {
        let window = parse_window("@3\x1f2\x1fapi\x1f1\x1f/tmp/project").unwrap();
        assert_eq!(window.id, "@3");
        assert_eq!(window.index, 2);
        assert_eq!(window.name, "api");
        assert!(window.active);
    }

    #[test]
    fn tmux_octal_escaped_separator_is_parsed() {
        let window = parse_window("@3\\0372\\037api\\0371\\037/tmp/project").unwrap();
        assert_eq!(window.id, "@3");
        assert_eq!(window.index, 2);
        assert_eq!(window.cwd.to_string_lossy(), "/tmp/project");
    }

    #[test]
    fn codex_launch_is_shell_quoted_and_returns_to_the_shell() {
        let command = codex_launch_command(
            Path::new("/tmp/Jordan's project"),
            Path::new("/tmp/codex home"),
            Path::new("/opt/Codex CLI/codex"),
            "thread_managed",
            "native-123",
            Path::new("/bin/zsh"),
        );
        assert!(command.contains("cd '/tmp/Jordan'\"'\"'s project'"));
        assert!(command.contains("CODEX_HOME='/tmp/codex home'"));
        assert!(command.contains("'/opt/Codex CLI/codex' resume 'native-123'"));
        assert!(command.ends_with("exec '/bin/zsh' -l"));
    }
}
